[package]
name = "robota-aggregate"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
mysql = "*"
rand = "0.8.4"
chrono = "0.4"
once_cell = "1.20.2"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
